config/routes.rb
Rails.application.routes.draw do
	root 'connections#index'
	resources :connections, except: :show
	devise_for :users
	resources :merge_restaurants do 
		resources :merge_locals
	end

	#Rutas Menu
	get "/menu",  :to => "merge_menus#index"
	post "/fetch_menu",  :to => "merge_menus#fetch_menu"
end

app/models/connection.rb
class Connection < ApplicationRecord
	#relaciones
	#has_one :merge_restaurant
	#validaciones
	validates :name, presence: true, uniqueness: true
	validates :name_db, presence: true, uniqueness: true
	validates :username_db, presence: true
    validates :password_db, presence: true
    validates :host_db, presence: true

	attribute :status, :boolean, default: true

	#Metodos
	def conexion_request(tiraSQL)
		ActiveRecord::Base.establish_connection({
			'adapter'=>'postgresql',
			'host'=> host_db,
			'username'=>username_db,
			'password'=>password_db,
			'database'=>name_db
		})
		data = ActiveRecord::Base.connection.execute(tiraSQL)
		ActiveRecord::Base.establish_connection :development
		return data
	end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :authenticate_user
  before_action :find_connection, only: [:edit, :update, :destroy]
  def index
    @connections = Connection.all.order(id: "DESC")
  end

  def new
    @connection = Connection.new
  end

  def create
    @connection = Connection.new(connection_params)
    if @connection.save
      flash[:alert] = "Conexion creada"
      redirect_to connections_path
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @connection.update(connection_params)
      flash[:alert] = "Conexion Actualizada"
      redirect_to connections_path
    end
  end

  def destroy
    if @connection.destroy
      flash[:alert] = "Conexion Eliminada"
      redirect_to connections_path
    end
  end

  private
    def connection_params
      params.require(:connection).permit(:name, :name_db, :password_db, :host_db, :username_db)
    end

    def authenticate_user
      if current_user == nil
        redirect_to new_user_session_path
      end
    end

    def find_connection
      @connection = Connection.find(params[:id])
    end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<%= form_for @connection do |f| %>
    <%= f.text_field :name %><br />
    <%= f.text_field :name_db %><br />
    <%= f.text_field :username_db %><br />
    <%= f.text_field :password_db %><br />
    <%= f.text_field :host_db %><br />
  
    <%= f.submit %>
<% end %>

<%= link_to "Regresar a la tabla de conexiones", connections_path %>

app/views/connections/edit.html.erb
<h1>Editar Conexiones</h1>
<%= render "form" %>

app/views/connections/index.html.erb
<h1>Tabla de conexiones a la BBDD de los Restaurantes </h1>

<table>
    <th>
      Nombre
    </th>
    <th>
      Nombre BBDD
    </th>
    <th>
      Usuario BBDD
    </th>
    <th>
      Password BBDD (encrypted)
    </th>
    <th>
      HOST_URL
    </th>
    <th>
      Estado
    </th>
    <th>
      Eliminar
    </th>
    <th>
      Editar Conexion
    </th>
    <% if @connections %>
      <% @connections.each do |connection| %>
        <tr>
          <td>
            <%= connection.name %>
          </td>
          <td>
            <%= connection.name_db %>
          </td>
          <td>
            <%= connection.username_db %>
          </td>
          <td>
            <%= connection.password_db %>
          </td>
          <td>
            <%= connection.host_db %>
          </td>
          <td>
            <%= connection.status %>
          </td>
          <td>
            <%= link_to "Eliminar", connection_path(connection), method: :delete %>
          </td>
          <td>
            <%= link_to "Editar", edit_connection_path(connection) %>
          </td>
        </tr>
      <% end %>
    <% end %>
</table>

<%= link_to "Nueva Conexion",  new_connection_path %>

app/views/connections/new.html.erb
<h1>Crear Nueva Conexion</h1>

<%= render "form" %>

app/views/connections/show.html.erb
<h1>Connections#show</h1>
<p>Find me in app/views/connections/show.html.erb</p>