config/routes.rb
Rails.application.routes.draw do
	root 'connections#index'
	resources :connections, except: :show
	devise_for :users
	resources :merge_restaurants do 
		resources :merge_locals
	end

	#Rutas Menu
	get "/menu",  :to => "merge_menus#index"
	post "/fetch_menu",  :to => "merge_menus#fetch_menu"
end

app/models/merge_local.rb
class MergeLocal < ApplicationRecord
	#relaciones
	belongs_to :merge_restaurant
	#validaciones
	validates :c_local_id, presence: true, uniqueness: true
	validates :prov_local_id, presence: true, uniqueness: true
	validates :merge_restaurant_id, presence: true
	validates :restaurant_token, presence: true, uniqueness: true
end

app/controllers/merge_locals_controller.rb
class MergeLocalsController < ApplicationController
  before_action :set_merge_restaurant
  before_action :set_merge_local, only: [:show, :edit, :update, :destroy]

  # GET /merge_locals
  # GET /merge_locals.json
  def index
    @merge_locals = @merge_restaurant.merge_locals
  end

  # GET /merge_locals/1
  # GET /merge_locals/1.json
  def show
  end

  # GET /merge_locals/new
  def new
    @merge_local = @merge_restaurant.merge_locals.new
  end

  # GET /merge_locals/1/edit
  def edit
  end

  # POST /merge_locals
  # POST /merge_locals.json
  def create
    @merge_local = @merge_restaurant.merge_locals.new(merge_local_params)
    respond_to do |format|
      if @merge_local.save
        format.html { redirect_to merge_restaurant_merge_locals_path(merge_restaurant_id: @merge_restaurant.id), notice: 'Merge local was successfully created.' }
        format.json { render :show, status: :created, location: @merge_local }
      else
        format.html { render :new }
        format.json { render json: @merge_local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merge_locals/1
  # PATCH/PUT /merge_locals/1.json
  def update
    respond_to do |format|
      if @merge_local.update(merge_local_params)
        format.html { redirect_to merge_restaurant_merge_local_path(merge_restaurant_id: @merge_restaurant.id, id: @merge_local.id), notice: 'Merge local was successfully updated.' }
        format.json { render :show, status: :ok, location: @merge_local }
      else
        format.html { render :edit }
        format.json { render json: @merge_local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merge_locals/1
  # DELETE /merge_locals/1.json
  def destroy
    @merge_local.destroy
    respond_to do |format|
      format.html { redirect_to merge_restaurant_merge_locals_path(merge_restaurant_id: @merge_restaurant.id), notice: 'Merge local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merge_local
      @merge_local = @merge_restaurant.merge_locals.find(params[:id])
    end

    #Objecto de merge_restaurant
    def set_merge_restaurant
      @merge_restaurant = MergeRestaurant.find(params[:merge_restaurant_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merge_local_params
      params.require(:merge_local).permit(:c_local_id, :prov_local_id, :merge_restaurant_id, :restaurant_token, :status)
    end
end

app/helpers/merge_locals_helper.rb
module MergeLocalsHelper
end

app/views/merge_locals/_form.html.erb
<%= form_with(model: [@merge_restaurant,merge_local], local: true) do |form| %>
  <% if merge_local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merge_local.errors.count, "error") %> prohibited this merge_local from being saved:</h2>

      <ul>
      <% merge_local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :c_local_id %>
    <%= form.number_field :c_local_id, id: :merge_local_c_local_id %>
  </div>

  <div class="field">
    <%= form.label :prov_local_id %>
    <%= form.number_field :prov_local_id, id: :merge_local_prov_local_id %>
  </div>

  <div class="field">
    <%= form.label :merge_restaurant_id %>
    <%= form.text_field :merge_restaurant_id, id: :merge_local_merge_restaurant_id %>
  </div>

  <div class="field">
    <%= form.label :restaurant_token %>
    <%= form.text_field :restaurant_token, id: :merge_local_restaurant_token %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :merge_local_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merge_locals/edit.html.erb
<h1>Editing Merge Local</h1>

<%= render 'form', merge_local: @merge_local %>

<%= link_to 'Show', @merge_local %> |
<%= link_to 'Back', merge_locals_path %>

app/views/merge_locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merge Locals</h1>

<table>
  <thead>
    <tr>
      <th>C local</th>
      <th>Prov local</th>
      <th>Merge restaurant</th>
      <th>Restaurant token</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merge_locals.each do |merge_local| %>
      <tr>
        <td><%= merge_local.c_local_id %></td>
        <td><%= merge_local.prov_local_id %></td>
        <td><%= merge_local.merge_restaurant.connection.name_db %></td>
        <td><%= merge_local.restaurant_token %></td>
        <td><%= merge_local.status %></td>
        <td><%= link_to 'Show', merge_restaurant_merge_local_path(merge_restaurant_id: @merge_restaurant.id, id: merge_local.id) %></td>
        <td><%= link_to 'Edit', edit_merge_restaurant_merge_local_path(merge_restaurant_id: @merge_restaurant.id, id: merge_local.id) %></td>
        <td><%= link_to 'Destroy', merge_restaurant_merge_local_path(merge_restaurant_id: @merge_restaurant.id, id: merge_local.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merge Local', new_merge_restaurant_merge_local_path(merge_restaurant_id: @merge_restaurant.id) %>

app/views/merge_locals/new.html.erb
<h1>New Merge Local</h1>

<%= render 'form', merge_local: @merge_local %>

<%= link_to 'Back', merge_restaurant_merge_locals_path(merge_restaurant_id: @merge_restaurant.id) %>

app/views/merge_locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>C local:</strong>
  <%= @merge_local.c_local_id %>
</p>

<p>
  <strong>Prov local:</strong>
  <%= @merge_local.prov_local_id %>
</p>

<p>
  <strong>Merge restaurant:</strong>
  <%= @merge_local.merge_restaurant %>
</p>

<p>
  <strong>Restaurant token:</strong>
  <%= @merge_local.restaurant_token %>
</p>

<p>
  <strong>Status:</strong>
  <%= @merge_local.status %>
</p>

<%= link_to 'Edit', edit_merge_local_path(@merge_local) %> |
<%= link_to 'Back', merge_locals_path %>