config/routes.rb
Rails.application.routes.draw do
	root 'connections#index'
	resources :connections, except: :show
	devise_for :users
	resources :merge_restaurants do 
		resources :merge_locals
	end

	#Rutas Menu
	get "/menu",  :to => "merge_menus#index"
	post "/fetch_menu",  :to => "merge_menus#fetch_menu"
end

app/models/merge_restaurant.rb
class MergeRestaurant < ApplicationRecord
	#relaciones
	belongs_to :connection
	has_many :merge_locals
	has_many :prov_merge_rests
	has_many :providers, through: :prov_merge_rests
	#validaciones
	validates :restaurant_key, presence: true, uniqueness: true
	validates :connection_id, presence: true, uniqueness: true
end

app/controllers/merge_restaurants_controller.rb
class MergeRestaurantsController < ApplicationController
  before_action :set_merge_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /merge_restaurants
  # GET /merge_restaurants.json
  def index
    @merge_restaurants = MergeRestaurant.all
  end

  # GET /merge_restaurants/1
  # GET /merge_restaurants/1.json
  def show
  end

  # GET /merge_restaurants/new
  def new
    @merge_restaurant = MergeRestaurant.new
  end

  # GET /merge_restaurants/1/edit
  def edit
  end

  # POST /merge_restaurants
  # POST /merge_restaurants.json
  def create
    @merge_restaurant = MergeRestaurant.new(merge_restaurant_params)

    respond_to do |format|
      if @merge_restaurant.save
        format.html { redirect_to @merge_restaurant, notice: 'Merge restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @merge_restaurant }
      else
        format.html { render :new }
        format.json { render json: @merge_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merge_restaurants/1
  # PATCH/PUT /merge_restaurants/1.json
  def update
    respond_to do |format|
      if @merge_restaurant.update(merge_restaurant_params)
        format.html { redirect_to @merge_restaurant, notice: 'Merge restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merge_restaurant }
      else
        format.html { render :edit }
        format.json { render json: @merge_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merge_restaurants/1
  # DELETE /merge_restaurants/1.json
  def destroy
    @merge_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to merge_restaurants_url, notice: 'Merge restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merge_restaurant
      @merge_restaurant = MergeRestaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merge_restaurant_params
      params.require(:merge_restaurant).permit(:restaurant_key, :connection_id, :status)
    end
end

app/helpers/merge_restaurants_helper.rb
module MergeRestaurantsHelper
end

app/views/merge_restaurants/_form.html.erb
<%= form_with(model: merge_restaurant, local: true) do |form| %>
  <% if merge_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merge_restaurant.errors.count, "error") %> prohibited this merge_restaurant from being saved:</h2>

      <ul>
      <% merge_restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :restaurant_key %>
    <%= form.text_field :restaurant_key, id: :merge_restaurant_restaurant_key %>
  </div>

  <div class="field">
    <%= form.label :connection_id %>
    <!-- <%= form.text_field :connection_id, id: :merge_restaurant_connection_id %> -->
    <%= select("merge_restaurant", "connection_id", Connection.all.collect {|c| [ c.name, c.id ] }, {include_blank: 'None'}) %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :merge_restaurant_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merge_restaurants/edit.html.erb
<h1>Editing Merge Restaurant</h1>

<%= render 'form', merge_restaurant: @merge_restaurant %>

<%= link_to 'Show', @merge_restaurant %> |
<%= link_to 'Back', merge_restaurants_path %>

app/views/merge_restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merge Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant key</th>
      <th>Connection</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merge_restaurants.each do |merge_restaurant| %>
      <tr>
        <td><%= merge_restaurant.restaurant_key %></td>
        <td><%= merge_restaurant.connection.name %></td>
        <td><%= merge_restaurant.status %></td>
        <td><%= link_to 'Show', merge_restaurant %></td>
        <td><%= link_to 'Edit', edit_merge_restaurant_path(merge_restaurant) %></td>
        <td><%= link_to 'Destroy', merge_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merge Restaurant', new_merge_restaurant_path %>

app/views/merge_restaurants/new.html.erb
<h1>New Merge Restaurant</h1>

<%= render 'form', merge_restaurant: @merge_restaurant %>

<%= link_to 'Back', merge_restaurants_path %>

app/views/merge_restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant key:</strong>
  <%= @merge_restaurant.restaurant_key %>
</p>

<p>
  <strong>Connection:</strong>
  <%= @merge_restaurant.connection.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @merge_restaurant.status %>
</p>

<%= link_to 'Edit', edit_merge_restaurant_path(@merge_restaurant) %> |
<%= link_to 'Back', merge_restaurants_path %>